services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=karla
      - POSTGRES_PASSWORD=nixindi
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
